/*
 *      epics2camac.h
*/

#ifndef _EPICS2CAMAC_H
#define _EPICS2CAMAC_H


BasicCycleRequest_t * assembleBasicRequest( int b, int c, int n, int a, int f );
CamacCycleRequestR_t assembleCamacRequestR( int b, int c, int n, int a, int f );
CamacCycleRequestW_t assembleCamacRequestW( int b, int c, int n, int a, int f, int32_t wdata );


    // typedef struct CamacRequestFrame {
    //     A_SET_OF(struct requesttype {
    //         requesttype_PR present;
    //         union CamacRequestFrame__requesttype_u {
    //             struct BasicCycleRequest	*requestR;
    //             struct CamacCycleRequestW	*requestW;
    //         } choice;
    //     
    //
    //         asn_struct_ctx_t _asn_ctx;
    //     } ) list;
        
    //     asn_struct_ctx_t _asn_ctx;
    // } CamacRequestFrame_t;


/* These two types have no definition in any of 
 * the header files generated by asn1c.
 * Seems unclean... I wonder if theres a better way.
 */
typedef union CamacRequestFrame__requesttype_u {
    CamacCycleRequestR_t	 requestR;
    CamacCycleRequestW_t	 requestW;
} CamacRequestFrame__requesttype_u_t;

typedef struct requesttype {
    requesttype_PR              present;
    CamacRequestFrame__requesttype_u_t   choice;    
    asn_struct_ctx_t            _asn_ctx;
} requesttype_t;



#endif
