/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EPICS2CAMAC"
 * 	found in "../epics2camac.asn1"
 * 	`asn1c -pdu=all -fincludes-quoted -fline-refs -fall-defs-global -findirect-choice -gen-PER -R`
 */

#ifndef	_BasicCycleRequest_H_
#define	_BasicCycleRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* BasicCycleRequest */
typedef struct BasicCycleRequest {
	long	 id;
	long	 b;
	long	 c;
	long	 n;
	long	 a;
	long	 f;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasicCycleRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasicCycleRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _BasicCycleRequest_H_ */
#include "asn_internal.h"
