/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EPICS2CAMAC"
 * 	found in "../epics2camac.asn1"
 * 	`asn1c -pdu=all -fincludes-quoted -fline-refs -fall-defs-global -findirect-choice -gen-PER -R`
 */

#ifndef	_CamacCycleReplyW_H_
#define	_CamacCycleReplyW_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BasicCycleRequest.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CamacCycleReplyW */
typedef struct CamacCycleReplyW {
	BasicCycleRequest_t	 requestW;
	long	 status;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CamacCycleReplyW_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CamacCycleReplyW;

#ifdef __cplusplus
}
#endif

#endif	/* _CamacCycleReplyW_H_ */
#include "asn_internal.h"
