/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EPICS2CAMAC"
 * 	found in "../epics2camac.asn1"
 * 	`asn1c -pdu=all -fincludes-quoted -fline-refs -fall-defs-global -findirect-choice -gen-PER -R`
 */

#include "CamacReplyFrame.h"

static asn_per_constraints_t asn_PER_type_replytype_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_replytype_2[] = {
	{ ATF_POINTER, 0, offsetof(struct replytype, choice.replyR),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CamacCycleReplyR,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"replyR"
		},
	{ ATF_POINTER, 0, offsetof(struct replytype, choice.replyW),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CamacCycleReplyW,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"replyW"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_replytype_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* replyRat 62 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* replyWat 64 */
};
static asn_CHOICE_specifics_t asn_SPC_replytype_specs_2 = {
	sizeof(struct replytype),
	offsetof(struct replytype, _asn_ctx),
	offsetof(struct replytype, present),
	sizeof(((struct replytype *)0)->present),
	asn_MAP_replytype_tag2el_2,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_replytype = {
	"CHOICE",
	"CHOICE",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_replytype_constr_2,
	asn_MBR_replytype_2,
	2,	/* Elements count */
	&asn_SPC_replytype_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CamacReplyFrame_1[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_replytype,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"replytype"
		},
};
static const ber_tlv_tag_t asn_DEF_CamacReplyFrame_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_CamacReplyFrame_specs_1 = {
	sizeof(struct CamacReplyFrame),
	offsetof(struct CamacReplyFrame, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
asn_TYPE_descriptor_t asn_DEF_CamacReplyFrame = {
	"CamacReplyFrame",
	"CamacReplyFrame",
	SET_OF_free,
	SET_OF_print,
	SET_OF_constraint,
	SET_OF_decode_ber,
	SET_OF_encode_der,
	SET_OF_decode_xer,
	SET_OF_encode_xer,
	SET_OF_decode_uper,
	SET_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CamacReplyFrame_tags_1,
	sizeof(asn_DEF_CamacReplyFrame_tags_1)
		/sizeof(asn_DEF_CamacReplyFrame_tags_1[0]), /* 1 */
	asn_DEF_CamacReplyFrame_tags_1,	/* Same as above */
	sizeof(asn_DEF_CamacReplyFrame_tags_1)
		/sizeof(asn_DEF_CamacReplyFrame_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CamacReplyFrame_1,
	1,	/* Single element */
	&asn_SPC_CamacReplyFrame_specs_1	/* Additional specs */
};

