/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EPICS2CAMAC"
 * 	found in "../epics2camac.asn1"
 * 	`asn1c -pdu=all -fincludes-quoted -fline-refs -fall-defs-global -findirect-choice -gen-PER -R`
 */

#include "CamacRequestFrame.h"

static asn_per_constraints_t asn_PER_type_requesttype_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_requesttype_2[] = {
	{ ATF_POINTER, 0, offsetof(struct requesttype, choice.requestR),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CamacCycleRequestR,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"requestR"
		},
	{ ATF_POINTER, 0, offsetof(struct requesttype, choice.requestW),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CamacCycleRequestW,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"requestW"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_requesttype_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* requestRat 34 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* requestWat 36 */
};
static asn_CHOICE_specifics_t asn_SPC_requesttype_specs_2 = {
	sizeof(struct requesttype),
	offsetof(struct requesttype, _asn_ctx),
	offsetof(struct requesttype, present),
	sizeof(((struct requesttype *)0)->present),
	asn_MAP_requesttype_tag2el_2,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_requesttype = {
	"CHOICE",
	"CHOICE",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_requesttype_constr_2,
	asn_MBR_requesttype_2,
	2,	/* Elements count */
	&asn_SPC_requesttype_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CamacRequestFrame_1[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_requesttype,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"requesttype"
		},
};
static const ber_tlv_tag_t asn_DEF_CamacRequestFrame_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_CamacRequestFrame_specs_1 = {
	sizeof(struct CamacRequestFrame),
	offsetof(struct CamacRequestFrame, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
asn_TYPE_descriptor_t asn_DEF_CamacRequestFrame = {
	"CamacRequestFrame",
	"CamacRequestFrame",
	SET_OF_free,
	SET_OF_print,
	SET_OF_constraint,
	SET_OF_decode_ber,
	SET_OF_encode_der,
	SET_OF_decode_xer,
	SET_OF_encode_xer,
	SET_OF_decode_uper,
	SET_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CamacRequestFrame_tags_1,
	sizeof(asn_DEF_CamacRequestFrame_tags_1)
		/sizeof(asn_DEF_CamacRequestFrame_tags_1[0]), /* 1 */
	asn_DEF_CamacRequestFrame_tags_1,	/* Same as above */
	sizeof(asn_DEF_CamacRequestFrame_tags_1)
		/sizeof(asn_DEF_CamacRequestFrame_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CamacRequestFrame_1,
	1,	/* Single element */
	&asn_SPC_CamacRequestFrame_specs_1	/* Additional specs */
};

