/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EPICS2CAMAC"
 * 	found in "../epics2camac.asn1"
 * 	`asn1c -pdu=all`
 */

#ifndef	_CamacCycleRequestR_H_
#define	_CamacCycleRequestR_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PduType.h"
#include "BasicCycleRequest.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CamacCycleRequestR */
typedef struct CamacCycleRequestR {
	PduType_t	 pduType;
	BasicCycleRequest_t	 basicCycle;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CamacCycleRequestR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CamacCycleRequestR;

#ifdef __cplusplus
}
#endif

#endif	/* _CamacCycleRequestR_H_ */
#include <asn_internal.h>
