/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EPICS2CAMAC"
 * 	found in "../epics2camac.asn1"
 * 	`asn1c -pdu=all`
 */

#ifndef	_CamacCycleRequestR_H_
#define	_CamacCycleRequestR_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BasicCycleRequest.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CamacCycleRequestR */
typedef BasicCycleRequest_t	 CamacCycleRequestR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CamacCycleRequestR;
asn_struct_free_f CamacCycleRequestR_free;
asn_struct_print_f CamacCycleRequestR_print;
asn_constr_check_f CamacCycleRequestR_constraint;
ber_type_decoder_f CamacCycleRequestR_decode_ber;
der_type_encoder_f CamacCycleRequestR_encode_der;
xer_type_decoder_f CamacCycleRequestR_decode_xer;
xer_type_encoder_f CamacCycleRequestR_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CamacCycleRequestR_H_ */
#include <asn_internal.h>
