/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EPICS2CAMAC"
 * 	found in "../epics2camac.asn1"
 * 	`asn1c -pdu=all`
 */

#ifndef	_CamacRequestFrame_H_
#define	_CamacRequestFrame_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include "CamacCycleRequestR.h"
#include "CamacCycleRequestW.h"
#include <constr_CHOICE.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum requesttype_PR {
	requesttype_PR_NOTHING,	/* No components present */
	requesttype_PR_requestR,
	requesttype_PR_requestW
} requesttype_PR;

/* CamacRequestFrame */
typedef struct CamacRequestFrame {
	A_SET_OF(struct requesttype {
		requesttype_PR present;
		union CamacRequestFrame__requesttype_u {
			CamacCycleRequestR_t	 requestR;
			CamacCycleRequestW_t	 requestW;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CamacRequestFrame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CamacRequestFrame;

#ifdef __cplusplus
}
#endif

#endif	/* _CamacRequestFrame_H_ */
#include <asn_internal.h>
