/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EPICS2CAMAC"
 * 	found in "../epics2camac.asn1"
 * 	`asn1c -pdu=all`
 */

#ifndef	_CamacCycleRequestW_H_
#define	_CamacCycleRequestW_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BasicCycleRequest.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CamacCycleRequestW */
typedef struct CamacCycleRequestW {
	BasicCycleRequest_t	 requestW;
	long	 wdata;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CamacCycleRequestW_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CamacCycleRequestW;

#ifdef __cplusplus
}
#endif

#endif	/* _CamacCycleRequestW_H_ */
#include <asn_internal.h>
