/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EPICS2CAMAC"
 * 	found in "../epics2camac.asn1"
 * 	`asn1c -pdu=all`
 */

#ifndef	_CamacReplyFrame_H_
#define	_CamacReplyFrame_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PduType.h"
#include "CamacCycleReplyR.h"
#include "CamacCycleReplyW.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum replytype_PR {
	replytype_PR_NOTHING,	/* No components present */
	replytype_PR_replyR,
	replytype_PR_replyW
} replytype_PR;

/* CamacReplyFrame */
typedef struct CamacReplyFrame {
	PduType_t	 pduType;
	struct replytype {
		replytype_PR present;
		union CamacReplyFrame__replytype_u {
			CamacCycleReplyR_t	 replyR;
			CamacCycleReplyW_t	 replyW;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} replytype;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CamacReplyFrame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CamacReplyFrame;

#ifdef __cplusplus
}
#endif

#endif	/* _CamacReplyFrame_H_ */
#include <asn_internal.h>
