/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_BasicCycleRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_CamacCycleRequestR;
extern struct asn_TYPE_descriptor_s asn_DEF_CamacCycleRequestW;
extern struct asn_TYPE_descriptor_s asn_DEF_CamacRequestFrame;
extern struct asn_TYPE_descriptor_s asn_DEF_CamacCycleReplyW;
extern struct asn_TYPE_descriptor_s asn_DEF_CamacCycleReplyR;
extern struct asn_TYPE_descriptor_s asn_DEF_CamacReplyFrame;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module EPICS2CAMAC in ../epics2camac.asn1 */
	&asn_DEF_BasicCycleRequest,	
	&asn_DEF_CamacCycleRequestR,	
	&asn_DEF_CamacCycleRequestW,	
	&asn_DEF_CamacRequestFrame,	
	&asn_DEF_CamacCycleReplyW,	
	&asn_DEF_CamacCycleReplyR,	
	&asn_DEF_CamacReplyFrame,	
	0
};

