/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EPICS2CAMAC"
 * 	found in "../epics2camac.asn1"
 * 	`asn1c -pdu=all`
 */

#include "PduType.h"

int
PduType_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
PduType_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

void
PduType_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	PduType_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
PduType_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	PduType_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
PduType_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	PduType_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
PduType_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	PduType_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
PduType_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	PduType_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
PduType_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	PduType_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static const asn_INTEGER_enum_map_t asn_MAP_PduType_value2enum_1[] = {
	{ 64,	10,	"basicCycle" },
	{ 65,	8,	"requestR" },
	{ 66,	8,	"requestW" },
	{ 67,	12,	"requestFrame" },
	{ 68,	6,	"replyR" },
	{ 69,	6,	"replyW" },
	{ 70,	10,	"replyFrame" },
	{ 71,	11,	"lamAnnounce" },
	{ 72,	6,	"lamAck" },
	{ 96,	13,	"errorAnnounce" },
	{ 97,	12,	"warnAnnounce" },
	{ 98,	12,	"infoAnnounce" },
	{ 99,	12,	"temperatureR" },
	{ 128,	9,	"registerR" },
	{ 129,	9,	"registerW" },
	{ 130,	12,	"registerResp" },
	{ 160,	9,	"reserved0" },
	{ 161,	9,	"reserved1" },
	{ 162,	9,	"reserved2" },
	{ 163,	9,	"reserved3" },
	{ 164,	9,	"reserved4" },
	{ 165,	9,	"reserved5" },
	{ 166,	9,	"reserved6" },
	{ 167,	9,	"reserved7" }
};
static const unsigned int asn_MAP_PduType_enum2value_1[] = {
	0,	/* basicCycle(64) */
	9,	/* errorAnnounce(96) */
	11,	/* infoAnnounce(98) */
	8,	/* lamAck(72) */
	7,	/* lamAnnounce(71) */
	13,	/* registerR(128) */
	15,	/* registerResp(130) */
	14,	/* registerW(129) */
	6,	/* replyFrame(70) */
	4,	/* replyR(68) */
	5,	/* replyW(69) */
	3,	/* requestFrame(67) */
	1,	/* requestR(65) */
	2,	/* requestW(66) */
	16,	/* reserved0(160) */
	17,	/* reserved1(161) */
	18,	/* reserved2(162) */
	19,	/* reserved3(163) */
	20,	/* reserved4(164) */
	21,	/* reserved5(165) */
	22,	/* reserved6(166) */
	23,	/* reserved7(167) */
	12,	/* temperatureR(99) */
	10	/* warnAnnounce(97) */
};
static const asn_INTEGER_specifics_t asn_SPC_PduType_specs_1 = {
	asn_MAP_PduType_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_PduType_enum2value_1,	/* N => "tag"; sorted by N */
	24,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_PduType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_PduType = {
	"PduType",
	"PduType",
	PduType_free,
	PduType_print,
	PduType_constraint,
	PduType_decode_ber,
	PduType_encode_der,
	PduType_decode_xer,
	PduType_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PduType_tags_1,
	sizeof(asn_DEF_PduType_tags_1)
		/sizeof(asn_DEF_PduType_tags_1[0]), /* 1 */
	asn_DEF_PduType_tags_1,	/* Same as above */
	sizeof(asn_DEF_PduType_tags_1)
		/sizeof(asn_DEF_PduType_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_PduType_specs_1	/* Additional specs */
};

