/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "EPICS2CAMAC"
 * 	found in "../epics2camac.asn1"
 * 	`asn1c -pdu=all`
 */

#ifndef	_PduType_H_
#define	_PduType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PduType {
	PduType_basicCycle	= 64,
	PduType_requestR	= 65,
	PduType_requestW	= 66,
	PduType_requestFrame	= 67,
	PduType_replyR	= 68,
	PduType_replyW	= 69,
	PduType_replyFrame	= 70,
	PduType_lamAnnounce	= 71,
	PduType_lamAck	= 72,
	PduType_errorAnnounce	= 96,
	PduType_warnAnnounce	= 97,
	PduType_infoAnnounce	= 98,
	PduType_temperatureR	= 99,
	PduType_registerR	= 128,
	PduType_registerW	= 129,
	PduType_registerResp	= 130,
	PduType_reserved0	= 160,
	PduType_reserved1	= 161,
	PduType_reserved2	= 162,
	PduType_reserved3	= 163,
	PduType_reserved4	= 164,
	PduType_reserved5	= 165,
	PduType_reserved6	= 166,
	PduType_reserved7	= 167
} e_PduType;

/* PduType */
typedef long	 PduType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PduType;
asn_struct_free_f PduType_free;
asn_struct_print_f PduType_print;
asn_constr_check_f PduType_constraint;
ber_type_decoder_f PduType_decode_ber;
der_type_encoder_f PduType_encode_der;
xer_type_decoder_f PduType_decode_xer;
xer_type_encoder_f PduType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PduType_H_ */
#include <asn_internal.h>
